/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as Descuento1RouteImport } from './routes/descuento1'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as MiembrosRouteImport } from './routes/miembros'
import { Route as Oferta1RouteImport } from './routes/oferta1'
import { Route as TesteRouteImport } from './routes/teste'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const Descuento1Route = Descuento1RouteImport.update({
  id: '/descuento1',
  path: '/descuento1',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const MiembrosRoute = MiembrosRouteImport.update({
  id: '/miembros',
  path: '/miembros',
  getParentRoute: () => rootRouteImport,
} as any)
const Oferta1Route = Oferta1RouteImport.update({
  id: '/oferta1',
  path: '/oferta1',
  getParentRoute: () => rootRouteImport,
} as any)
const TesteRoute = TesteRouteImport.update({
  id: '/teste',
  path: '/teste',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/descuento1': typeof Descuento1Route
  '/gracias': typeof GraciasRoute
  '/miembros': typeof MiembrosRoute
  '/oferta1': typeof Oferta1Route
  '/teste': typeof TesteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/descuento1': typeof Descuento1Route
  '/gracias': typeof GraciasRoute
  '/miembros': typeof MiembrosRoute
  '/oferta1': typeof Oferta1Route
  '/teste': typeof TesteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/descuento1': typeof Descuento1Route
  '/gracias': typeof GraciasRoute
  '/miembros': typeof MiembrosRoute
  '/oferta1': typeof Oferta1Route
  '/teste': typeof TesteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/descuento1'
    | '/gracias'
    | '/miembros'
    | '/oferta1'
    | '/teste'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/descuento1'
    | '/gracias'
    | '/miembros'
    | '/oferta1'
    | '/teste'
  id:
    | '__root__'
    | '/'
    | '/acceso'
    | '/descuento1'
    | '/gracias'
    | '/miembros'
    | '/oferta1'
    | '/teste'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoRoute: typeof AccesoRoute
  Descuento1Route: typeof Descuento1Route
  GraciasRoute: typeof GraciasRoute
  MiembrosRoute: typeof MiembrosRoute
  Oferta1Route: typeof Oferta1Route
  TesteRoute: typeof TesteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descuento1': {
      id: '/descuento1'
      path: '/descuento1'
      fullPath: '/descuento1'
      preLoaderRoute: typeof Descuento1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miembros': {
      id: '/miembros'
      path: '/miembros'
      fullPath: '/miembros'
      preLoaderRoute: typeof MiembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta1': {
      id: '/oferta1'
      path: '/oferta1'
      fullPath: '/oferta1'
      preLoaderRoute: typeof Oferta1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teste': {
      id: '/teste'
      path: '/teste'
      fullPath: '/teste'
      preLoaderRoute: typeof TesteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoRoute: AccesoRoute,
  Descuento1Route: Descuento1Route,
  GraciasRoute: GraciasRoute,
  MiembrosRoute: MiembrosRoute,
  Oferta1Route: Oferta1Route,
  TesteRoute: TesteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
